### ISSUE TITLE
Error inflating class com.google.android.gms.ads.AdView

### ISSUE THREAD

**Issue by ryosoftware** [dandar3/android-google-play-services-ads#4] opened 2017-11-22 17:39 UTC
Hello,

I have included this project (and also the four dependences) in my workspace.
Compiled the libraries and included in my app, but the app refuses to run due to the AdView class is not defined.

The app is working fine with the 8.29 version of the Google Play Services (the last version that G has relased to be used with Eclipse)

Do you know what's the issue?

Thanks

11-22 18:35:29.422  2760  2760 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.google.android.gms.ads.AdView
11-22 18:35:29.422  2760  2760 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
11-22 18:35:29.422  2760  2760 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
11-22 18:35:29.422  2760  2760 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
11-22 18:35:29.422  2760  2760 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
11-22 18:35:29.422  2760  2760 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
11-22 18:35:29.422  2760  2760 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)

**Comment by dandar3** [comment] 2017-11-22 22:41
@robertoprubio 
- What version of the library are you using? just assuming 11.4.0
- What version of Android API is it running on?
- Is it a larger stack trace with multiple `Caused by`, if so can you share the entire stack trace please.
- Can you share your XML definition at line #9 (replacing any sensitive information).
- Does it work if you add the banner programatically?
https://developers.google.com/android/reference/com/google/android/gms/ads/AdView

PS: Easiest way to download all libraries in a set into your workspace is using Team Sets, see https://github.com/dandar3/android-google-play-services-README page and particularly the videos at the end. You just need to add `google-play-services-ads` as an Android library to your project (in project Properties).

**Comment by ryosoftware** [comment] 2017-11-27 11:44
Sorry, I took advantage of the weekend to start migrating my apps to android-studio, but I will try to reproduce the error and post.
Thanks anyway

**Comment by dandar3** [comment] 2018-05-27 15:31
Closing for now.

**Closed as completed by dandar3** 2018-05-27 15:31 UTC
